dnbr_cat_names:
  - "Enhanced Regrowth"
  - "Unburned"
  - "Low Severity"
  - "Moderate Severity"
  - "High Severity"

nbr_colors:
  - "g"
  - "yellowgreen"
  - "peachpuff"
  - "coral"
  - "maroon"

nbr_cmap:
    - "g"
    - "yellowgreen"
    - "peachpuff"
    - "coral"
    - "maroon"
    - "black"

dnbr_class_bins:
  - -1000
  - -0.1
  - 0.1
  - 0.27
  - 0.66
  - 1000

pre_fire:
  - "sentinel"

post_fire:
    - "sentinel"

satellite:
  - "sentinel"

output_path:
  - "output"