dnbr_cat_names:
  - "Enhanced Regrowth"
  - "Unburned"
  - "Low Severity"
  - "Moderate Severity"
  - "High Severity"

nbr_colors:
  - "#778835"
  - "#a7c050"
  - "#0be344"
  - "#f8fc11"
  - "#f8b140"
  - "#f8671a"
  - "#a600d4"
  - "black"

dnbr_class_bins:
  - -0.5
  - -0.25
  - -0.1
  - 0.1
  - 0.27
  - 0.44
  - 0.66
  - 1.3

pre_fire:
  - "sentinel/R20m_20230604"

post_fire:
    - "sentinel/R20m_20231007"

satellite:
  - "sentinel"

output_path:
  - "output"