dnbr_cat_names:
  - "Enhanced Regrowth"
  - "Unburned"
  - "Low Severity"
  - "Moderate Severity"
  - "High Severity"

nbr_colors:
  - "black"
  - "#778835"
  - "#a7c050"
  - "#0be344"
  - "#f8fc11"
  - "#f8b140"
  - "#f8671a"
  - "#a600d4"

dnbr_class_bins:
  - -0.5
  - -0.25
  - -0.1
  - 0.1
  - 0.27
  - 0.44
  - 0.66
  - 1.3

method:
  #- "nbr"
  - "nbr+"


pre_fire:
  - "sentinel"
  #- "bc_burn"

post_fire:
  - "sentinel2"
  #- "bc_burn2"

satellite:
  - "sentinel"
  #- "landsat"

output_path:
  - "output"